# Generated by Django 2.2.6 on 2020-02-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20200126_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expire',
            field=models.BooleanField(default=True),
        ),
    ]
