# Generated by Django 2.2.6 on 2020-02-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_coupon_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire',
            field=models.BooleanField(default=False),
        ),
    ]
